### ISSUE TITLE
2012 15-MBPR/Core X/1080 and Titan Black egpu setup doesn’t always persist after reboot

### ISSUE THREAD

**Issue by markedphillips** [mayankk2308/purge-nvda#12]
I’ve done clean installs and setup purge-wrangler/purge-nvidia/set-egpu and after reboots system doesn’t reboot all the time. I’ve uninstalled and reinstalled, but the system doesn’t seem stable. What are some possible configuration of hardware issues or sequences I maybe missing?

**Comment by mayankk2308** [comment]
Sometimes after applying purge-nvda, the mux may not be set correctly. The behavior occurs due undeterminable/unknown behavior with that mux setting/EFI. In such a case, Use the Set Mux to iGPU option again. The most stable configuration on such Macs is on Sierra (10.12.x). Also note that for your configuration, purge-nvda is only required to resolve OpenCL/GL issues. System should work fine without this script otherwise.
